spring:
  datasource:
    source01:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.1.111:3306/samh_sensorsdata_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: root123
    source02:
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      jdbc-url: jdbc:clickhouse://192.168.1.111:8123/samh_sensorsdata_test?socket_timeout=10000

  redis:
    host: localhost
    port: 6379
    password: aibanproject
    timeout: 30000 #连接超时时间（毫秒）
    database: 0 #默认是索引为0的数据库
    lettuce:    #lettuce连接池
      pool:
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 10 # 连接池中的最大空闲连接 默认 8
        min-idle: 10 # 连接池中的最小空闲连接 默认 0
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制） 默认 8
  kafka:
    bootstrap-servers: 192.168.1.111:9092,192.168.1.111:9093,192.168.1.111:9094
    #自定义的topic
    myMsgTopic: ^(samh_applog_json_.*|samh_applog_undefined_event|samh_applog_merge_content_exposure|service_.*)$

#是否开启swagger
swagger:
  enable: true

logback:
  level: INFO
  log_path: ../personal/src/main/resources/log/

load_cache_at_start: false
un_auth: true

upload:
  path: ../personal/

